# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df80516024105995aa1324e813867d5df74e2621acceb5dccddd699108a1f6219dbcc0c20bae1c2043cef6af5378dce852fecffcf09c14c98fa86f01e25690a

test:
  secret_key_base: 83dab3bf67a00563c94cd5fd03fbde27ebba25d03b741cdd962a082abc11e51648f42b11026c63f850e3689707d6c401f50e72f5aef748d04fc73ffd71e543da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
